[build]
  builder = "nixpacks"
  buildCommand = "npm cache clean --force && npm install --omit=dev --no-cache"

[deploy]
  startCommand = "node index.js"
  healthcheckPath = "/health"
  restartPolicy = "on-failure"
  maxRetries = 3

[env]
  NODE_ENV = "production"
