[build]
  builder = "nixpacks"
  buildCommand = "npm ci --only=production"

[deploy]
  startCommand = "node index.js"
  healthcheckPath = "/health"
  healthcheckTimeout = 100
  restartPolicy = "on-failure"
  maxRetries = 3

[env]
  NODE_ENV = "production"