[build]
  builder = "nixpacks"
  buildCommand = "npm run build"

[deploy]
  startCommand = "npm run start"
  healthcheckPath = "/health"
  healthcheckTimeout = 100
  restartPolicy = "on-failure"
  maxRetries = 3

[env]
  NODE_ENV = "production"
